Data-Type in NumPy Arrays

Installing Numpy

In [202]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


Import Numpy

In [203]:
import numpy as np
print(np.__version__)

2.4.6


Numpy 1D , 2D and 3D Array

In [204]:
#1D array
a1D=np.array([1,2,3,4,5])
a1D

array([1, 2, 3, 4, 5])

In [205]:
type(a1D)

numpy.ndarray

In [206]:
#if we want to learn more about numpy array
help(np.array)

Help on built-in function array in module numpy:

array(
    object,
    dtype=None,
    *,
    copy=True,
    order='K',
    subok=False,
    ndmin=0,
    ndmax=0,
    like=None
)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          ndmax=0, like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if 

In [207]:
#print detail
a1D.shape #length

(5,)

In [208]:
a1D.size

5

In [209]:
len(a1D) # all give just length 

5

In [210]:
#2D Array ==> list of list / mattrix
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [211]:
arr.shape # 2 rows 4 coln

(2, 4)

In [212]:
arr.size # total number of element

8

In [213]:
len(arr) # number of rows

2

In [214]:
#3d array
a3D_lst=[
    [
        [1,2] , [3,4]
    ],[
        [5,6] , [7,8]
    ]
]
# how to calculte this is 3d array just count left square bracket from top till 1st right bracket come n left braket tat means nd array
arr = np.array(a3D_lst)
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [215]:
arr.shape

(2, 2, 2)

In [216]:
arr.size

8

In [217]:
len(arr)

2

Note ==> Numpy array  are homogeneous , meaning all element must be of the same data type

In [218]:
arr=np.array([1,2,3])
arr
np.array([1,2,3] , dtype = np.int32)

array([1, 2, 3], dtype=int32)

In [219]:
np.array([1.2,4.5,6.8])
np.array([1.2,4.5,6.8] , dtype = np.float32)

array([1.2, 4.5, 6.8], dtype=float32)

In [220]:
np.array([1.2,4.5,6.8])
np.array([1.2,4.5,6.8] , dtype = np.int32) #casting

array([1, 4, 6], dtype=int32)

In [221]:
np.array([True , False ,True])


array([ True, False,  True])

In [222]:
np.array([True , False , True], dtype=np.int32) # True =1 and False=0

array([1, 0, 1], dtype=int32)

In [223]:
np.array(["Dharmesh" , "Sharma"])
np.array(["Dharmesh , Sharma"] , dtype="U6")

array(['Dharme'], dtype='<U6')

let try with some hetrogenous element

In [224]:
np.array([1,2.6,"Dharmesh"])
#numpy is more intelligent it will convert all other element in string automaticaaly and make array again homogenous

array(['1', '2.6', 'Dharmesh'], dtype='<U32')

In [225]:
np.array([1,2.6,"98765"] , dtype=np.int32)


array([    1,     2, 98765], dtype=int32)

In [226]:
#np.array([1,2.6,"Dharmesh"] , dtype=np.int32)
#give value error

Record array or Structered Array

In [227]:
#List of Tupple
records=[
    ("Dharmesh" , 50 , 100),
    ("Ankit" , 301 , 100),
    ("Sahil", 44 , 50)
]
records

[('Dharmesh', 50, 100), ('Ankit', 301, 100), ('Sahil', 44, 50)]

In [228]:
data=np.array(records , dtype=[("name","U20"),("Rollno",np.int32),("marks",int)])
data

array([('Dharmesh',  50, 100), ('Ankit', 301, 100), ('Sahil',  44,  50)],
      dtype=[('name', '<U20'), ('Rollno', '<i4'), ('marks', '<i8')])

In [229]:
#Let print element with index value
data[0] # if we want to avoid extra message in output we will use print 
print(data[0])

('Dharmesh', 50, 100)


In [230]:
#let print specfic element
print(data["name"])
print(data["Rollno"])
print(data["marks"])

['Dharmesh' 'Ankit' 'Sahil']
[ 50 301  44]
[100 100  50]


It can support heterogenous types using objects arrays or structured dtypes , but these loose most perfromance benefits

In [231]:
het = np.array([5,4.5,True,"d"]) # auto type cast in str
het

array(['5', '4.5', 'True', 'd'], dtype='<U32')

In [232]:
het.dtype

dtype('<U32')

In [233]:
het[0] # 5 is int but output show in str

np.str_('5')

In [234]:
#let covert np.array in to object array
het=np.array([5,4.5,True,"d"] , dtype=object)
het # output is hetrogenous form beaucse object array is similar to list in python there are all different dtypes now

array([5, 4.5, True, 'd'], dtype=object)

In [235]:
het.dtype

dtype('O')

In [236]:
het[0]

5

In [237]:
print(type(het[0]))

<class 'int'>


In [238]:
print(het) # allomost similar to list in python no auto casting bu numpy

[5 4.5 True 'd']


As we create a object array it will lose most performance beenfit

Ways to Create NUmpy Array

In [239]:
import numpy as np

In [240]:
#using list
np.array([1,2,3])

array([1, 2, 3])

In [241]:
#using tupple
np.array((1,2,3))

array([1, 2, 3])

Upcasting in numpy

In [242]:
np.array([1,2.5,3,4])
#convert whole array in to float so there is no loss of .5

array([1. , 2.5, 3. , 4. ])

Minimum 2D

In [243]:
np.array([1,2,3,4] , ndmin=2)
#force to change dimension in 1D to 2D so numpy will add just nohter list and amke it more nested

array([[1, 2, 3, 4]])

In [244]:
np.array([1,2,3,4] , dtype=complex)
#so again there is no loss of value this is property of numpy that he will maintain array homogenous or give value error 

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

data connsisting of more than 1 data type

In [245]:
np.array(((1,2.8,3),(9.5,8,7)))
#more than 1 data type i.e int and float

array([[1. , 2.8, 3. ],
       [9.5, 8. , 7. ]])

In [246]:
arr=np.array([(1.5,2),(9.7,8)] , dtype=[("a",int),("b",float)])
print(arr["a"]) #first coln
print(arr["b"]) # second coln

[1 9]
[2. 8.]


In [247]:
#if we wont many data type in array then we use record/structure in array
record=[
    ["Dharmesh",1,1.6,True],
    ["Ankit",1,5.7,False],
    ["Abhishek",0,0.1,False]
    ]

arr=np.array(record)
print(arr)

[['Dharmesh' '1' '1.6' 'True']
 ['Ankit' '1' '5.7' 'False']
 ['Abhishek' '0' '0.1' 'False']]


np.asarray

In [248]:
np.asarray([1,2,3])

array([1, 2, 3])

In [249]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [250]:
np.asarray in a #false
#check with coln
np.asarray(a) in a #True

True

if dtype is set , array is copied only if dtype does not match

In [251]:
np.array([1,2] , dtype=np.float32)

array([1., 2.], dtype=float32)

In [252]:
np.asarray(a , dtype=np.float64) is a

False

numpy.copy

In [253]:
a=np.array([1,2] , dtype=np.float32)

In [254]:
np.array(a,copy=True) is a #by default
# output is false beacyse i will create a new array 

False

In [255]:
np.array(a,copy=False) is a
#now we can't copy so there is change in main array only

True

create a array x with a reference y and a copy z

In [256]:
x = np.array([1,2,3])
y=x # refernce not copy i.e both x and y will point same array in memory it is like a np.asarray

In [257]:
z=np.copy(x) # it behave like np.array and create another new array rather than existing array
z

array([1, 2, 3])

what if we modify x and y but not z

In [258]:
x=np.array([1,2])
y=x
y

array([1, 2])

In [259]:
z=np.array(x)
z

array([1, 2])

In [260]:
#modify y
x[0]=22
x

array([22,  2])

In [261]:
# let see now x
y

array([22,  2])

In [262]:
#let se change in z
z
# as z in copy of old x so if we change x now it will no effect to z baecuse z in completly different array

array([1, 2])

Read and write data from file
txt files (.txt) (.csv)

In [263]:
data=np.loadtxt("data.txt" , delimiter=",") # delimiter hai jiise list of list seperate ho 
data

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.],
       [5., 7., 4., 2.]])

In [264]:
data=data**2
data

array([[ 1.,  4.,  9., 16.],
       [25., 36., 49., 64.],
       [25., 49., 16.,  4.]])

In [265]:
np.savetxt("output_data.txt", data , fmt="%d")# fmt =%f it will give in float format

binaray files(.npy, .np)

In [266]:
arr=np.array([1,2,3,4])
np.save("array.npy",arr) # we can't read binary file with noraml txt reader

In [267]:
arr=np.load("array.npy")
print(arr)

[1 2 3 4]


In [268]:
#save multiple file
# not possible in txt file  only possible in binary file
a=np.array([1,2,3])
b=np.array([5,6,7])
np.savez("multi_array.npz", arr1=a , arr2=b)
#use savez to save multi file and npz

In [269]:
arr=np.load("multi_array.npz")
print(arr["arr1"])
print(arr["arr2"])

[1 2 3]
[5 6 7]


numpy.fromfunction

In [270]:
np.fromfunction(lambda i,j: i==j , (3,3), dtype=int)


array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

A new 1D array ('1 2' , dtype=int , sep='  ')

In [ ]:
np.fromstring("1 2", dtype=int , sep=" ")#blank space

array([1, 2])

create a record array from a (flat) list of arrat

In [276]:
x1 = [1,2,3] #int
x2=[4.0,5.0,6.0] #float
x3=["a","b","c"] # str
# expected output [int,float,str]

In [279]:
a=list(zip(x1,x2,x3))#list of tuple
a

[(1, 4.0, 'a'), (2, 5.0, 'b'), (3, 6.0, 'c')]

In [ ]:
np.array(a)
# r=np.array(list(zip(x1,x2,x3)), dtype =[("a=i4"),("b"=f4),("c"="U1")])
#x1=a,x2=b,x3=c
#r[a]


array([['1', '4.0', 'a'],
       ['2', '5.0', 'b'],
       ['3', '6.0', 'c']], dtype='<U32')

Data type

In [284]:
my_lst=[1,2,3]
arr=np.array(my_lst)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3]


In [290]:
my_mat=[[1,2,3], [4,5,6],[7,8,9]]
arr = np.array(my_mat)
print(type(arr))
print(arr)
print(arr.ndim ,sep= ' ') # Dimesion
arr.size #use sep also
arr.shape
arr.dtype

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


dtype('int64')

Creating Numpy Arrays and Matrix Using Built_in Function

In [2]:
#arrange and linespace
import numpy as np

In [ ]:
#range(start,stop,step)
#np.arange(start,stop,step , dtype)


In [1]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
np.arange(0,100,5 , dtype= np.int32)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95], dtype=int32)

In [9]:
np.arange(0,10,0.1,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

np.linearspace (linspace)

In [ ]:
#np.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None , axis=0)
print("21 lineraly space number between 1 and 5/n ---------------------")

np.linspace(1,5,21)

21 lineraly space number between 1 and 5/n ---------------------


array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ])

In [13]:
np.linspace(1,10,40, dtype= np.float32 )

array([ 1.       ,  1.2307693,  1.4615384,  1.6923077,  1.9230769,
        2.1538463,  2.3846154,  2.6153846,  2.8461537,  3.0769231,
        3.3076923,  3.5384614,  3.7692308,  4.       ,  4.230769 ,
        4.4615383,  4.6923075,  4.923077 ,  5.1538463,  5.3846154,
        5.6153846,  5.8461537,  6.076923 ,  6.3076925,  6.5384617,
        6.769231 ,  7.       ,  7.230769 ,  7.4615383,  7.6923075,
        7.923077 ,  8.153846 ,  8.384615 ,  8.615385 ,  8.846154 ,
        9.076923 ,  9.307693 ,  9.538462 ,  9.769231 , 10.       ],
      dtype=float32)

np.logspace()

In [ ]:
#np.logspace(start,stop,num=50,endpoint=True,base=10.0,dtype=None)
 #np.linspace(start,stop) gives valueevenly spaced in linear space.
# np.logspace(start,stop gives values evenly spaced in logarithimic space)

np.logspace(1,10,10) # 10 value between 1 ,10 accroding to there ratio

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

In [17]:
np.logspace(start=1,stop=6,num=10,base=2,dtype=int)

array([ 2,  2,  4,  6,  9, 13, 20, 29, 43, 64])

numpy array and matrix creation

In [18]:
print("Vector of zeroes\n ------------------------")
np.zeros(5) # n=5

Vector of zeroes
 ------------------------


array([0., 0., 0., 0., 0.])

In [20]:
print("matrix of zeroes \n----------------------------------")
np.zeros((5,5)) #2d

matrix of zeroes 
----------------------------------


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
print("Vector of onces\n -------------------")
np.ones(6)

Vector of onces
 -------------------


array([1., 1., 1., 1., 1., 1.])

In [23]:
print("Matrix of ones\n---------------------------")
np.ones((3,4), dtype=int)

Matrix of ones
---------------------------


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [25]:
print("Matrix of 5's\n-----------------------------")
np.ones((3,3) , dtype=np.int32)*5



Matrix of 5's
-----------------------------


array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]], dtype=int32)

In [ ]:
print('Empty matrix\n------------------------')
np.empty((3,4)) #kuch bhi ho sakta hai garbage value

Empty matrix
------------------------


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

np.reshape

Diagonal , Trigangular , Lower Trigangular and Upper Trigangular

In [34]:
arr=np.array(((1,1,1),(2,2,2),(3,3,3)))
arr

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [39]:
print("Diagonal matrix----------------")
np.diag(arr)

Diagonal matrix----------------


array([1, 2, 3])

In [40]:
print("Lower triagangular matrix--------------------------")
np.tril(arr)

Lower triagangular matrix--------------------------


array([[1, 0, 0],
       [2, 2, 0],
       [3, 3, 3]])

In [41]:
print("Upper trigangular matrix-----------")
np.triu(arr)

Upper trigangular matrix-----------


array([[1, 1, 1],
       [0, 2, 2],
       [0, 0, 3]])

let's implement this for rectangular matrix

In [42]:
a=np.array(((1,1,1),(2,2,2),(3,3,3),(4,4,4)))
a

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [43]:
print("Diagonal matrix----------------")
np.diag(a)

Diagonal matrix----------------


array([1, 2, 3])

In [47]:
print("Lower triagangular matrix--------------------------")
np.tril(a)

Lower triagangular matrix--------------------------


array([[1, 0, 0],
       [2, 2, 0],
       [3, 3, 3],
       [4, 4, 4]])

In [48]:
print("Upper trigangular matrix-----------")
np.triu(a)

Upper trigangular matrix-----------


array([[1, 1, 1],
       [0, 2, 2],
       [0, 0, 3],
       [0, 0, 0]])

Python is smart enough to handle this type of situtation

In [46]:
#what if we want diaginal matrix
np.diag(np.diag(arr))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

np.eyes()
np.eyes(N ,M=None, k=0,dtype=float,order="C")

In [50]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

Accessing diagonal in Numpy
use np.diag(n,k)

In [51]:
print(np.arange(9))

[0 1 2 3 4 5 6 7 8]


In [53]:
print(np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#main Diagonal
np.diag(np.diag(((1,1,1),(2,2,2),(3,3,3))))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [66]:
# above 1 main diagonal
np.diag(np.diag(((1,1,1),(2,2,2),(3,3,3))) , 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [67]:
#below diagonal
np.diag(np.diag(((1,1,1),(2,2,2),(3,3,3))),-1)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

Random numbers generation

In [ ]:
print(np.random.rand(1,6))
#uniform

[[0.87682719 0.34090511 0.89354906 0.14975397 0.85461511 0.5599317 ]]


In [ ]:
#normal
print(np.random.randn(2,3))
# graph jaisa postive negative or zero

[[-0.25788205  0.56003612  0.57547809]
 [-0.46512295 -0.78474483  0.05264753]]


In [ ]:
print("Random interger-----------")
print(np.random.randint(1,100,5))
# k==5

Random interger-----------
[77 84 93 68 97]


In [ ]:
# if we want in matrix format
print(np.random.randint(1,100,(4,4)))
# k= 4,4

[[34 22 37  5]
 [44 16 23 60]
 [ 9 66 14 58]
 [73 88 27 84]]


In [77]:
#let throw dice for 20 time
print(np.random.randint(1,7,20))

[1 2 2 3 6 4 2 4 4 1 3 3 6 5 3 1 6 4 4 5]
